### PR TITLE
Add `ellipsis` char; respect `maxdepth` for printing

### LINKED ISSUE #37: `print_tree` does not respect `maxdepth`
Nested trees print forever, which is confirmed by searching for `maxdepth` in the code and not finding it used!

### PR DESCRIPTION
**Pull request by ericphanson**
Fixes #37. I added an `ellipsis` field to `TreeCharSet` to control how it prints a final set of children after `maxdepth` has been reached, which I guess makes this breaking, since custom `TreeCharSet`'s won't work unless they add an ellipsis field too. I could add a default constructor that uses `…` as the ellipsis, if this is a concern.

Before:
```julia
ephwork:AbstractTrees eh540$ julia --project=. examples/fstree.jl
AbstractTrees
├─ .git
│  ├─ FETCH_HEAD
│  ├─ HEAD
│  ├─ config
│  ├─ description
│  ├─ hooks
│  │  └─ README.sample
│  ├─ index
│  ├─ info
│  │  └─ exclude
│  ├─ logs
│  │  ├─ HEAD
│  │  └─ refs
│  │     ├─ heads
│  │     │  └─ master
│  │     └─ remotes
│  │        ├─ cache
│  │        │  ├─ heads
│  │        │  │  ├─ fbot
│  │        │  │  │  └─ deps
│  │        │  │  ├─ kf
│  │        │  │  │  └─ for06
│  │        │  │  └─ master
│  │        │  └─ pull
│  │        │     ├─ 1
│  │        │     │  └─ head
│  │        │     ├─ 13
│  │        │     │  └─ head
│  │        │     ├─ 14
│  │        │     │  └─ head
│  │        │     ├─ 16
│  │        │     │  └─ head
│  │        │     ├─ 19
│  │        │     │  └─ head
│  │        │     ├─ 2
│  │        │     │  └─ head
│  │        │     ├─ 21
│  │        │     │  └─ head
│  │        │     ├─ 22
│  │        │     │  ├─ head
│  │        │     │  └─ merge
│  │        │     ├─ 24
│  │        │     │  └─ head
│  │        │     ├─ 28
│  │        │     │  └─ head
│  │        │     ├─ 3
│  │        │     │  └─ head
│  │        │     ├─ 30
│  │        │     │  └─ head
│  │        │     ├─ 31
│  │        │     │  └─ head
│  │        │     ├─ 32
│  │        │     │  ├─ head
│  │        │     │  └─ merge
│  │        │     ├─ 33
│  │        │     │  ├─ head
│  │        │     │  └─ merge
│  │        │     ├─ 34
│  │        │     │  ├─ head
│  │        │     │  └─ merge
│  │        │     ├─ 35
│  │        │     │  ├─ head
│  │        │     │  └─ merge
│  │        │     ├─ 4
│  │        │     │  └─ head
│  │        │     ├─ 5
│  │        │     │  └─ head
│  │        │     ├─ 6
│  │        │     │  └─ head
│  │        │     ├─ 7
│  │        │     │  └─ head
│  │        │     ├─ 8
│  │        │     │  └─ head
│  │        │     └─ 9
│  │        │        └─ head
│  │        └─ origin
│  │           ├─ fbot
│  │           │  └─ deps
│  │           ├─ kf
│  │           │  └─ for06
│  │           └─ master
│  ├─ objects
│  │  ├─ info
│  │  └─ pack
│  │     ├─ pack-2532b66dca90e4401f3ee6d0efe50825d67681be.idx
│  │     ├─ pack-2532b66dca90e4401f3ee6d0efe50825d67681be.pack
│  │     ├─ pack-98edf7935288bf8050dc9b46d3ca1043200deccb.idx
│  │     └─ pack-98edf7935288bf8050dc9b46d3ca1043200deccb.pack
│  └─ refs
│     ├─ heads
│     │  └─ master
│     ├─ remotes
│     │  ├─ cache
│     │  │  ├─ heads
│     │  │  │  ├─ fbot
│     │  │  │  │  └─ deps
│     │  │  │  ├─ kf
│     │  │  │  │  └─ for06
│     │  │  │  └─ master
│     │  │  └─ pull
│     │  │     ├─ 1
│     │  │     │  └─ head
│     │  │     ├─ 13
│     │  │     │  └─ head
│     │  │     ├─ 14
│     │  │     │  └─ head
│     │  │     ├─ 16
│     │  │     │  └─ head
│     │  │     ├─ 19
│     │  │     │  └─ head
│     │  │     ├─ 2
│     │  │     │  └─ head
│     │  │     ├─ 21
│     │  │     │  └─ head
│     │  │     ├─ 22
│     │  │     │  ├─ head
│     │  │     │  └─ merge
│     │  │     ├─ 24
│     │  │     │  └─ head
│     │  │     ├─ 28
│     │  │     │  └─ head
│     │  │     ├─ 3
│     │  │     │  └─ head
│     │  │     ├─ 30
│     │  │     │  └─ head
│     │  │     ├─ 31
│     │  │     │  └─ head
│     │  │     ├─ 32
│     │  │     │  ├─ head
│     │  │     │  └─ merge
│     │  │     ├─ 33
│     │  │     │  ├─ head
│     │  │     │  └─ merge
│     │  │     ├─ 34
│     │  │     │  ├─ head
│     │  │     │  └─ merge
│     │  │     ├─ 35
│     │  │     │  ├─ head
│     │  │     │  └─ merge
│     │  │     ├─ 4
│     │  │     │  └─ head
│     │  │     ├─ 5
│     │  │     │  └─ head
│     │  │     ├─ 6
│     │  │     │  └─ head
│     │  │     ├─ 7
│     │  │     │  └─ head
│     │  │     ├─ 8
│     │  │     │  └─ head
│     │  │     └─ 9
│     │  │        └─ head
│     │  └─ origin
│     │     ├─ fbot
│     │     │  └─ deps
│     │     ├─ kf
│     │     │  └─ for06
│     │     └─ master
│     └─ tags
│        ├─ v0.0.1
│        ├─ v0.0.2
│        ├─ v0.0.3
│        ├─ v0.0.4
│        ├─ v0.1.0
│        ├─ v0.2.0
│        └─ v0.2.1
├─ .gitignore
├─ .travis.yml
├─ LICENSE.md
├─ README.md
├─ REQUIRE
├─ examples
│  └─ fstree.jl
├─ src
│  ├─ AbstractTrees.jl
│  ├─ implicitstacks.jl
│  └─ traits.jl
└─ test
   └─ runtests.jl
```

After:

```julia
ephwork:AbstractTrees eh540$ julia --project=. examples/fstree.jl
AbstractTrees
├─ .git
│  ├─ FETCH_HEAD
│  ├─ HEAD
│  ├─ config
│  ├─ description
│  ├─ hooks
│  │  └─ README.sample
│  ├─ index
│  ├─ info
│  │  └─ exclude
│  ├─ logs
│  │  ├─ HEAD
│  │  └─ refs
│  │     ├─ heads
│  │     │  └─ master
│  │     └─ remotes
│  │        ├─ cache
│  │        │  ├─ …
│  │        │  └─ …
│  │        └─ origin
│  │           ├─ …
│  │           ├─ …
│  │           └─ …
│  ├─ objects
│  │  ├─ info
│  │  └─ pack
│  │     ├─ pack-2532b66dca90e4401f3ee6d0efe50825d67681be.idx
│  │     ├─ pack-2532b66dca90e4401f3ee6d0efe50825d67681be.pack
│  │     ├─ pack-98edf7935288bf8050dc9b46d3ca1043200deccb.idx
│  │     └─ pack-98edf7935288bf8050dc9b46d3ca1043200deccb.pack
│  └─ refs
│     ├─ heads
│     │  └─ master
│     ├─ remotes
│     │  ├─ cache
│     │  │  ├─ heads
│     │  │  │  ├─ …
│     │  │  │  ├─ …
│     │  │  │  └─ …
│     │  │  └─ pull
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     ├─ …
│     │  │     └─ …
│     │  └─ origin
│     │     ├─ fbot
│     │     │  └─ …
│     │     ├─ kf
│     │     │  └─ …
│     │     └─ master
│     └─ tags
│        ├─ v0.0.1
│        ├─ v0.0.2
│        ├─ v0.0.3
│        ├─ v0.0.4
│        ├─ v0.1.0
│        ├─ v0.2.0
│        └─ v0.2.1
├─ .gitignore
├─ .travis.yml
├─ LICENSE.md
├─ README.md
├─ REQUIRE
├─ examples
│  └─ fstree.jl
├─ src
│  ├─ AbstractTrees.jl
│  ├─ implicitstacks.jl
│  └─ traits.jl
└─ test
   └─ runtests.jl
```

### CODE REVIEW

**Comment by timholy** [comment]
Thanks for the PR! Probably due to #22 it's now got conflicts, unfortunately. Some tests would be lovely!

**Comment by timholy** [comment]
I fixed the conflict, hopefully correctly.

In my opinion, breaking changes are not something to worry too much about given that we now require upper bounds in `[compat]` entries.

Aside from tests, another improvement would be to document the required fields of `charset`.

**Comment by jonalm** [comment]
Oh, I didn't notice this PR before I submitted #42, that fix does not add ellipsis but prints the as a terminal node. #42  offers a modest test which may be suitable for this pr. Need to adjust the number of prited lines to account for the ellipsis. Consider 
```
struct SingleChildInfiniteDepth end
AbstractTrees.children(::SingleChildInfiniteDepth) = (SingleChildInfiniteDepth(),)

function num_printed_lines(node, maxdepth)
    buffer = IOBuffer()
    print_tree(buffer, node, maxdepth)
    printed_text = String(take!(buffer))
    length([l for l in split(printed_text, '\n') if ~isempty(l)])
end

# should print 'maxdepth + 1' number of lines (one for each layer pluss the original node)
@test num_printed_lines(SingleChildInfiniteDepth(), 3) == 4
@test num_printed_lines(SingleChildInfiniteDepth(), 10) == 11
```
(comment slightly altered)

**Comment by ericphanson** [comment]
Sorry, I’ve been quite busy and don’t have time to help finish this PR right now. I’d happy for someone to take over. I can also try to find time to finish this up in a couple weeks.

We’ve vendored a copy of this function in Convex.jl to add this change and also a `maxwidth` parameter. It would be great to get that upstreamed too, but maybe that’s for a separate PR.

**Comment by jonalm** [comment]
My two cents is that, it is nice that the ellipsis indicates that the tree contains nodes which aren't printed, but  that it is annoying that it prints a whole bunch of ellipsis in cases where you have many children (like in the fstree example above).

**Comment by ericphanson** [comment]
I agree that it’s a bit annoying in the example above, but I think adding a maxwidth parameter might be a good solution. My motivation is for `show` methods of tree-like objects where you really don’t want to overwhelm the users repl when they don’t use a semicolon, but also want to be explicit when something is truncated.

**Comment by ericphanson** [comment]
> My two cents is that, it is nice that the ellipsis indicates that the tree contains nodes which aren't printed, but that it is annoying that it prints a whole bunch of ellipsis in cases where you have many children (like in the fstree example above).

Just to say I only now realize what you mean by the "whole bunch of ellipsis"-- totally agree, and I like the vertical ellipsis fix you made in #42. I'll close this one in favor of that.

**Pull request closed without merging**
